
(setq mode 'light)

(let ((base03      "#262626")
      (base02      "#303030")
      (base01      "#586e75")
      (base00      "#657b83")
      (base0       "#839496")
      (base1       "#93a1a1")
      (base2       "#eee8d5")
      (base3       "#fdf6e3")
      (yellow      "#b58900")
      (orange      "#cb4b16")
      (red         "#dc322f")
      (magenta     "#d33682")
      (violet      "#6c71c4")
      (blue        "#268bd2")
      (cyan        "#2aa198")
      (green       "#859900")
      (fmt-none `(:weight normal :slant normal  :underline nil        :inverse-video nil))
      )
  (when (eq 'light mode)
    (rotatef base03 base3)
    (rotatef base02 base2)
    (rotatef base01 base1)
    (rotatef base00 base0))

  (set-face-attribute 'show-paren-match        nil :foreground blue :background nil :weight 'bold)
  (set-face-attribute 'show-paren-mismatch     nil :foreground red :background nil :weight 'bold)

  (setq-default evil-default-cursor '(base01 bar))

  ;; helm
  (set-face-attribute 'helm-header             nil :foreground base0 :background base02)
  (set-face-attribute 'helm-source-header      nil :foreground base0 :background base02)
  (set-face-attribute 'helm-M-x-key            nil :foreground orange :background base03)
  (set-face-attribute 'helm-buffer-size        nil :foreground magenta :background base03)
  (set-face-attribute 'helm-match              nil :foreground base03 :background yellow)
  (set-face-attribute 'helm-grep-match         nil :foreground base03 :background yellow)
  (set-face-attribute 'helm-ff-directory       nil :foreground blue :background base03)
  (set-face-attribute 'helm-ff-file            nil :foreground base0 :background base03)
  (set-face-attribute 'helm-ff-executable      nil :foreground green :background base03)
  (set-face-attribute 'helm-ff-invalid-symlink nil :foreground red :background base03)
  (set-face-attribute 'helm-ff-symlink         nil :foreground cyan :background base03)
  (set-face-attribute 'helm-grep-cmd-line      nil :foreground yellow :background base03)
  (set-face-attribute 'helm-grep-file          nil :foreground base0 :background base03)
  (set-face-attribute 'helm-grep-lineno        nil :foreground cyan :background base03)
  (set-face-attribute 'helm-selection          nil :background base02 :underline nil)
  (set-face-attribute 'helm-selection-line     nil :background base02 :underline nil)
  (set-face-attribute 'helm-grep-finish        nil :foreground red :background base02)
  (set-face-attribute 'helm-grep-running       nil :foreground green :background base02)
  (set-face-attribute 'helm-candidate-number   nil :foreground yellow :background base02)
  )
