
(setq mode 'light)

(let ((base03      "#002b36")
      (base02      "#073642")
      (base01      "#586e75")
      (base00      "#657b83")
      (base0       "#839496")
      (base1       "#93a1a1")
      (base2       "#eee8d5")
      (base3       "#fdf6e3")
      (yellow      "#b58900")
      (orange      "#cb4b16")
      (red         "#dc322f")
      (magenta     "#d33682")
      (violet      "#6c71c4")
      (blue        "#268bd2")
      (cyan        "#2aa198")
      (green       "#859900")
      (light-blue  "#d1f5ea")
      (fmt-none `(:weight normal :slant normal  :underline nil        :inverse-video nil))
      )
  (when (eq 'light mode)
    (rotatef base03 base3)
    (rotatef base02 base2)
    (rotatef base01 base1)
    (rotatef base00 base0))

  (set-face-attribute 'show-paren-match        nil :foreground base02 :background blue :weight 'normal)
  (set-face-attribute 'show-paren-mismatch     nil :foreground base02 :background red :weight 'normal)
  (set-face-attribute 'region                  nil :foreground base02 :background blue :inverse-video nil)
  (set-face-attribute 'lazy-highlight          nil :foreground base02 :background blue :inverse-video nil)
  (set-face-attribute 'isearch                 nil :foreground base02 :background magenta :inverse-video nil)
  (set-face-attribute 'linum                   nil :background base02 :inverse-video nil)

  (setq-default evil-default-cursor '(base01 bar))

  ;; helm
  (set-face-attribute 'helm-header             nil :foreground base0 :background base02)
  (set-face-attribute 'helm-source-header      nil :foreground base0 :background base02)
  (set-face-attribute 'helm-M-x-key            nil :foreground orange :background base03)
  (set-face-attribute 'helm-buffer-size        nil :foreground magenta :background base03)
  (set-face-attribute 'helm-match              nil :foreground base02 :background blue)
  (set-face-attribute 'helm-grep-match         nil :foreground base02 :background blue)
  (set-face-attribute 'helm-ff-directory       nil :foreground blue :background base03)
  (set-face-attribute 'helm-ff-file            nil :foreground base1 :background nil)
  (set-face-attribute 'helm-ff-executable      nil :foreground green :background base03)
  (set-face-attribute 'helm-ff-invalid-symlink nil :foreground red :background base03)
  (set-face-attribute 'helm-ff-symlink         nil :foreground cyan :background base03)
  (set-face-attribute 'helm-grep-cmd-line      nil :foreground yellow :background base03)
  (set-face-attribute 'helm-grep-file          nil :foreground base0 :background base03)
  (set-face-attribute 'helm-grep-lineno        nil :foreground cyan :background base03)
  (set-face-attribute 'helm-selection          nil :foreground base02 :background blue :underline nil)
  (set-face-attribute 'helm-selection-line     nil :foreground base02 :background blue :underline nil)
  (set-face-attribute 'helm-grep-finish        nil :foreground orange :background base02)
  (set-face-attribute 'helm-grep-running       nil :foreground green :background base02)
  (set-face-attribute 'helm-candidate-number   nil :foreground yellow :background base02)
)
