;; everything todo with vim emulation

(add-to-list 'load-path "~/.emacs.d/site-lisp/vimpulse")
(require 'vimpulse)
(define-key viper-vi-diehard-map "\C-v" 'vimpulse-visual-toggle-block)
(define-key viper-vi-basic-map "\C-u" 'viper-scroll-down)
(define-key viper-insert-basic-map (kbd "C-S-h") 'delete-backward-char)
(define-key key-translation-map [?\C-h] [?\C-?])
(vimpulse-omap "re" 'find-alternate-file)
(vimpulse-map "_" (lambda ()
                    (interactive)
                    (vimpulse-visual-toggle-line)
                    (comment-or-uncomment-region (line-beginning-position) (line-end-position))
                    (vimpulse-visual-toggle-line)
                    (viper-next-line 1)))
(vimpulse-map "-" 'comment-dwim)
(vimpulse-map "o" (lambda ()
                    (interactive)
                    (viper-open-line 1)
                    (indent-according-to-mode)))
(vimpulse-map "O" (lambda ()
                    (interactive)
                    (viper-Open-line 1)
                    (indent-according-to-mode)))

(vimpulse-map "zE" 'anything-find-file-other-window)
(vimpulse-map "ze" 'anything-find-file)
(vimpulse-map "zB" 'viper-switch-to-buffer-other-window)
(vimpulse-map "zb" 'viper-switch-to-buffer)
(vimpulse-map "zw" 'save-buffer)
(vimpulse-map "zq" 'save-buffers-kill-terminal)
(vimpulse-map "zcd" 'cd)
(vimpulse-map "zV" 'split-window-vertically)
(vimpulse-map "zH" 'split-window-horizontally)
(vimpulse-map "zx" 'delete-window)
(vimpulse-map "zd" 'kill-this-buffer)
(vimpulse-map "zi" 'imenu)
(vimpulse-map "zo" 'other-window)
(vimpulse-map "zh" 'windmove-left)
(vimpulse-map "zl" 'windmove-right)
(vimpulse-map "zj" 'windmove-down)
(vimpulse-map "zk" 'windmove-up)
(vimpulse-map "H" 'windmove-left)
(vimpulse-map "L" 'windmove-right)
(vimpulse-map "J" 'windmove-down)
(vimpulse-map "K" 'windmove-up)
(vimpulse-map "za" 'align-current)
(vimpulse-vmap "za" 'align)
(vimpulse-map "zA" 'align-regexp)
(vimpulse-vmap "zA" 'align-regexp)

(vimpulse-map  [tab] 'indent-line)
(vimpulse-vmap [tab] 'indent-line)
;; (vimpulse-imap [tab] 'indent-for-tab-command)
(define-key viper-vi-basic-map [tab] 'indent-for-tab-command)
(vimpulse-imap [C-tab] 'tab-to-tab-stop)
(define-key viper-vi-basic-map "`" 'elscreen-select-and-goto)

(defadvice viper-maybe-checkout (around viper-svn-checkin-fix activate)
      "Advise viper-maybe-checkout to ignore svn files."
      (let ((file (expand-file-name (buffer-file-name buf))))
        (when (and (featurep 'vc-hooks)
                   (not (memq (vc-backend file) '(nil SVN Git))))
          ad-do-it)))

