(deftheme asht
  "Created 2013-03-12.")

(custom-theme-set-faces
 'asht
 '(default ((t (:family "DejaVu Sans Mono" :foundry "unknown" :width normal :height 107 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#CDCDCD" :background "#323232" :stipple nil :inherit nil))))
 '(cursor ((t (:background "#A4CD28"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#E6DB74"))))
 '(minibuffer-prompt ((t (:foreground "#89BDEF"))))
 '(highlight ((t (:background "#C4BE89" :foreground "#000000"))))
 '(region ((t (:background "#000000"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((t (:background "#272822"))))
 '(trailing-whitespace ((((class color) (background light)) (:background "red1")) (((class color) (background dark)) (:background "red1")) (t (:inverse-video t))))
 '(font-lock-builtin-face ((t (:foreground "#A4CD28"))))
 '(font-lock-comment-delimiter-face ((t (:slant italic :foreground "#646464"))))
 '(font-lock-comment-face ((t (:foreground "#646464"))))
 '(font-lock-constant-face ((t (:foreground "#6D28CD"))))
 '(font-lock-doc-face ((t (:slant italic :foreground "#646464"))))
 '(font-lock-function-name-face ((t (:foreground "#CD2851"))))
 '(font-lock-keyword-face ((t (:foreground "#A4CD28"))))
 '(font-lock-negation-char-face ((t (:weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "#CD5128"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight bold))))
 '(font-lock-regexp-grouping-construct ((t (:weight bold))))
 '(font-lock-string-face ((t (:foreground "#CD28A4"))))
 '(font-lock-type-face ((t (:foreground "#28A4CD"))))
 '(font-lock-variable-name-face ((t (:foreground "#A4CD28"))))
 '(font-lock-warning-face ((t (:background "#333333" :foreground "#FFFFFF"))))
 '(button ((t (:inherit (link)))))
 '(link ((((class color) (min-colors 88) (background light)) (:underline t :foreground "RoyalBlue3")) (((class color) (background light)) (:underline t :foreground "blue")) (((class color) (min-colors 88) (background dark)) (:underline t :foreground "cyan1")) (((class color) (background dark)) (:underline t :foreground "cyan")) (t (:inherit (underline)))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:background "#232526"))))
 '(header-line ((default (:inherit (mode-line))) (((type tty)) (:underline t :inverse-video nil)) (((class color grayscale) (background light)) (:box nil :foreground "grey20" :background "grey90")) (((class color grayscale) (background dark)) (:box nil :foreground "grey90" :background "grey20")) (((class mono) (background light)) (:underline t :box nil :inverse-video nil :foreground "black" :background "white")) (((class mono) (background dark)) (:underline t :box nil :inverse-video nil :foreground "white" :background "black"))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:box (:line-width 1 :color "#A4CD28" :style nil) :background "#323232" :foreground "#191919"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box (:line-width 1 :color "#191919" :style nil) :background "#323232" :foreground "#191919"))))
 '(isearch ((t (:background "#293739"))))
 '(isearch-fail ((t (:background "#333333" :foreground "#FFFFFF"))))
 '(lazy-highlight ((t (:background "#293739"))))
 '(match ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "RoyalBlue3")) (((class color) (min-colors 8) (background light)) (:foreground "black" :background "yellow")) (((class color) (min-colors 8) (background dark)) (:foreground "white" :background "blue")) (((type tty) (class mono)) (:inverse-video t)) (t (:background "gray"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'asht)
